workflow with Docker integration

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Deploy HTML Website
+name: CI/CD Pipeline
 
 on:
   push:
@@ -7,14 +7,48 @@ on:
   workflow_dispatch:
 
 jobs:
-  deploy:
+
+  build_and_push_docker:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Deploy via FTP
+      # Vérification de structure HTML
+      - name: Vérification HTML
+        run: |
+          if ! grep -iq "<html" index.html; then
+            echo "Erreur : fichier HTML invalide."
+            exit 1
+          fi
+
+      # Connexion à Docker Hub
+      - name: Login Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      # Build de l'image Docker
+      - name: Build Docker image
+        run: |
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/tresor_ethere:latest .
+
+      # Push de l'image vers DockerHub
+      - name: Push Docker image
+        run: |
+          docker push ${{ secrets.DOCKER_USERNAME }}/tresor_ethere:latest
+
+  deploy_ftp:
+    runs-on: ubuntu-latest
+    needs: build_and_push_docker
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Deploy to InfinityFree via FTP
         uses: SamKirkland/FTP-Deploy-Action@v4.0.0
         with:
           server: ${{ secrets.FTP_SERVER }}
